sudo: required
services:
  - docker
before_install:
  - docker build -t rodrigofbm/docker-react -f Dockerfile.dev .

script:
  - docker run rodrigofbm/docker-react npm test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "<S3/region_url>"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"