sudo: required
services:
  - docker
before_install:
  - docker build -t rodrigofbm/docker-react -f Dockerfile.dev .

script:
  - docker run rodrigofbm/docker-react npm test -- --coverage --watchAll=false
